RMS.Web/Models/StudentInfo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentFatherName { get; set; }
        public int StudentAge { get; set; }
        public string StudentEmail { get; set; }
        public long Fathercnic { get; set; }
        public string FatherOcp { get; set; }
        public string FatherEmail { get; set; }
        public string FatherNumber { get; set; }
        public string Course { get; set; }
        public string Branch { get; set; }
        public System.TimeSpan Timings { get; set; }
    }
}

RMS.Web/Controllers/StudentInfoController.cs
using RMS.Web.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMS.Web.Models;

namespace RMS.Web.Controllers
{
    public class StudentInfoController : Controller
    {
        StudentInfoServices services = new StudentInfoServices();
        // GET: StudentInfo
        public ActionResult Index()
        {
            var studentlist = services.GetallStudents();
            return View(studentlist);
        }
        [HttpPost]
        public ActionResult SaveStudents(StudentInfo studentInfo , int Studentid=0)
        {
            if (Studentid > 0)
            {
                var dbstudent = services.Getstudentbyid(Studentid);
                studentInfo.StudentID = Studentid;

                dbstudent.StudentName = studentInfo.StudentName;
                dbstudent.StudentFatherName = studentInfo.StudentFatherName;
                dbstudent.StudentAge = studentInfo.StudentAge;
                dbstudent.StudentEmail = studentInfo.StudentEmail;
                dbstudent.Fathercnic = studentInfo.Fathercnic;
                dbstudent.FatherOcp = studentInfo.FatherOcp;
                dbstudent.FatherEmail = studentInfo.FatherEmail;
                dbstudent.FatherNumber = studentInfo.FatherNumber;
                dbstudent.Course = studentInfo.Course;
                dbstudent.Branch = studentInfo.Branch;
                dbstudent.Timings = studentInfo.Timings;



                services.UpdateStudent(dbstudent);
                    return RedirectToAction("Index");
            }

            else {
                services.AddStudent(studentInfo);
                return RedirectToAction("Index");

            }


        }

        public ActionResult Getstudent( StudentInfo student, int studentid = 0)
        {
            
               var stdid = services.Getstudentbyid(studentid);
                return Json(stdid, JsonRequestBehavior.AllowGet);
            
        }
        public ActionResult DeleteStudent(int Studentid=0)
        {
            if(Studentid>0)
            {
                var student = services.Getstudentbyid(Studentid);
                services.deletestudent(student);
                return RedirectToAction("Index");

            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        

    }
}

RMS.Web/Views/StudentInfo/Index.cshtml
@model List<RMS.Web.Models.StudentInfo>
    
@{

    ViewBag.Title = "Index";
}

<div class="container-fluid">
    <br /><br />
    <div class="row">
        <div class="col-md-4">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" id="btnAddf">Add Student</button>
        </div>
        <div class="col-md-8">
            <h3 style="margin:0;float:left;" class="text-center">Student Info</h3>
        </div>

    </div>
    <hr />

    <table class="table table-bordered table-condensed table-responsive table-striped">
        <thead style="background-color:darkturquoise">
            <tr>
                <td hidden>
                    StudentID
                </td>
                <td>
                    Student Name
                </td>
                <td> Student FatherName </td>
                <td> Student Age</td>
                <td>Student Email </td>
                <td> Father CNIC</td>
                <td>Father Ocupation </td>
                <td> Father Email </td>
                <td> Father Number </td>
                <td> Course </td>
                <td> Branch </td>
                <td> Timings </td>
                <td>Actions</td>
            </tr>

        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td >@item.StudentName</td>
                        <td>@item.StudentFatherName </td>
                        <td> @item.StudentAge</td>
                        <td>@item.StudentEmail  </td>
                        <td>@item.Fathercnic </td>
                        <td>@item.FatherOcp </td>
                        <td>@item.FatherEmail  </td>
                        <td>@item.FatherNumber </td>
                        <td>@item.Course</td>
                        <td>@item.Branch</td>
                        <td>@item.Timings</td>
                        <td><button data-id="@item.StudentID" class="btn btn-success btnedit"><i class="glyphicon glyphicon-edit"></i>Edit</button>
                        <button data-id="@item.StudentID" class="btn btn-danger btndelete"><i class="glyphicon glyphicon-remove"></i>Delete</button>     
                        
                        </td>
                    </tr>
                }


            }
        </tbody>




    </table>


</div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title text-center" id="exampleModalLabel"><strong>Add Student</strong></h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.Partial("View")
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="btnSave" type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>





<script>
    $('#btnSave').click(function () {
        //var StudentInfo = {}

        //StudentInfo.studentid = $('#StudentID').val();
        //StudentInfo.StudentName = $('#StudentName').val();
        //StudentInfo.studentFatherName = $('#StudentFatherName').val();
        //StudentInfo.StudentAge = $('#StudentAge').val();
        //StudentInfo.StudentEmail = $('#StudentEmail').val();
        //StudentInfo.Fathercnic = $('#Fathercnic').val();
        //StudentInfo.FatherOcp = $('#FatherOcp').val();
        //StudentInfo.FatherEmail = $('#FatherEmail').val();
        //StudentInfo.FatherNumber = $('#FatherNumber').val();
        //StudentInfo.Course = $('#Course').val();
        //StudentInfo.Branch = $('#Branch').val();
        //StudentInfo.Timings = $('#Timings').val();


        $.ajax({
            type: 'POST',
            url: "@Url.Action("SaveStudents", "StudentInfo")",
            //dataType: 'JSON',
            //contentType: 'application/json, charset=utf-8',
            data: $('#studentForm').serialize()

        }).done(function (data) {
            alert("data inserted Successfully");
            location.reload();
        }).fail(function (jqXHR, textStatus) {
            alert("data inserted Successfully");
            location.reload();

        });
    });

    $('.btnedit').click(function () {
        var Studentid = $(this).attr("data-id");
        $.ajax({
            type: 'GET',
            url: "@Url.Action("Getstudent","StudentInfo")",
            data: { studentid: Studentid }


        }).done(function (data) {
            $('#StudentID').val(Studentid);
            $('#StudentName').val(data.StudentName);
            $('#StudentFatherName').val(data.StudentFatherName);
            $('#StudentAge').val(data.StudentAge);
            $('#StudentEmail').val(data.StudentEmail);
            $('#Fathercnic').val(data.Fathercnic);
            $('#FatherOcp').val(data.FatherOcp);
            $('#FatherEmail').val(data.FatherEmail);
            $('#FatherNumber').val(data.FatherNumber);
            $('#Course').val(data.Course);
            $('#Branch').val(data.Branch);
            $('#Timings').val(data.Timings);

            $('#exampleModal').modal("show");


            alert("data catch Successfully");
        }).fail(function (jqXHR, textStatus) {
            alert("data Updated Successfully");
            location.reload();

        });




    });


    $('.btndelete').click(function () {
        var stdid = $(this).attr("data-id");


        $.ajax({
            type: 'GET',
            data: { Studentid: stdid },
            url: "@Url.Action("DeleteStudent","StudentInfo")",

        }).done(function (data) {
            $(this).parent().parent().remove();
            alert("data deletedd Successfully");
            location.reload();
        }).fail(function (jqXHR, textStatus) {
            alert("data delete fail  Successfully");
            location.reload();

        });





    });




</script>

RMS.Web/Views/StudentInfo/View.cshtml
<form id="studentForm">
    <div class="row">
        <input type="hidden" hidden="hidden" name="StudentID" class="form-control" id="StudentID" />
        <div class="form-group">


            <label class="col-sm-2">Student Name</label>
            <div class="col-sm-4">
                <input type="text" name="StudentName" required class="form-control " id="StudentName" />
            </div>
            <label class="col-sm-2">Student FatherName</label>
            <div class="col-sm-4">
                <input type="text" name="StudentFatherName" class="form-control" id="StudentFatherName" />
            </div>
        </div>
        <br />

        <label class="col-sm-2">Student Age</label>
        <div class="col-sm-4">
            <input type="number" name="StudentAge" class="form-control " id="StudentAge" />
        </div>
        <br />

        <label class="col-sm-2">Student Email</label>
        <div class="col-sm-4">
            <input type="email" name="StudentEmail" class="form-control " id="StudentEmail" />
        </div>
        <hr />


        <div class="form-group">
            <label class="col-md-2">Father CNIC</label>
            <div class="col-md-4">
                <input type="number" name="Fathercnic" class="form-control  " id="Fathercnic" />
            </div>
            <label class="col-md-2">Father Ocupation</label>
            <div class="col-md-4">

                <input type="text" name="FatherOcp" class="form-control " id="FatherOcp" />
            </div>

            <br />
        </div>

        <div class="form-group">
            <label class="col-md-2">Father Email</label>
            <div class="col-md-4">

                <input type="email" name="FatherEmail" class="form-control " id="FatherEmail" />
            </div>
            <br />
            <label class="col-md-2">Father Number</label>
            <div class="col-md-4">

                <input type="tel" name="FatherNumber" class="form-control " id="FatherNumber" />
            </div>

            <hr />
        </div>

        <div class="form-group">


            <label class="col-md-2">Course</label>
            <div class="col-md-4">

                <input type="text" name="Course" class="form-control " id="Course" />
            </div>
            <br />
            <label class="col-md-2">Branch</label>
            <div class="col-md-4">

                <input type="text" name="Branch" class="form-control " id="Branch" />
            </div>

            <br />
        </div>
        <div class="">

            <label class="col-md-2">Timings</label>
        
        <div class="col-md-4">
            <input type="time" name="Timings" class="form-control" id="Timings" />
        </div>
        </div>


        
    </div>
</form>