RMS.Web/Models/Account.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.JournalVoucherChild = new HashSet<JournalVoucherChild>();
            this.VoucherMaster = new HashSet<VoucherMaster>();
        }
    
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public string Alias { get; set; }
        public string Print_Name { get; set; }
        public int LedgerTypeid { get; set; }
        public Nullable<int> SubledgeraccountID { get; set; }
        public int Accgroupid { get; set; }
        public int CurrencyID { get; set; }
        public long Opening_Balance { get; set; }
        public string Address { get; set; }
        public int CountryID { get; set; }
        public Nullable<long> CNIC { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<long> mobileNum { get; set; }
        public string email { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<int> SubledgerGroupID { get; set; }
        public string SubledgerGroupName { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<double> CreditTotal { get; set; }
        public Nullable<double> DebitTotal { get; set; }
    
        public virtual AccGroup AccGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalVoucherChild> JournalVoucherChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherMaster> VoucherMaster { get; set; }
    }
}

RMS.Web/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RMS.Web.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }


    public class UserPrivilegeViewModel
    {
        public List<AspNetUsers> UserDetails { get; set; }
        public List<MenuItems> MenuItems { get; set; }
        public List<int> ExistingAssignedMenuIds { get; set; }
        public int SelectedUserId { get; set; }

        public RegisterViewModel registerViewModel { get; set; }
    }


    public class AddUserPrivilegeModel
    {
        public int UserId { get; set; }
        public List<int?> MenuIds { get; set; }
        public string Replace { get; set; }
    }
    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "UserName")]
        public string Email { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }

        [Required]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
        public int? locationid { get; set; }
        public int Userid{ get; set; }
        public string Id { get; set; }



        public List<MenuItems> Menulists { get; set; }

        public AspNetUsers Users { get; set; }
        public List<UsersMenu> Usersmenu { get; set; }

        public RegisterViewModel registerViewModel { get; set; }

    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

RMS.Web/Models/Currency.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Currency()
        {
            this.JournalVoucherChild = new HashSet<JournalVoucherChild>();
        }
    
        public int CurrencyID { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
        public string CurrencyShortName { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> LowRate { get; set; }
        public Nullable<double> HighRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalVoucherChild> JournalVoucherChild { get; set; }
    }
}

RMS.Web/Controllers/MastersController.cs
using CrystalDecisions.CrystalReports.Engine;
using RMS.Web.Models;
using RMS.Web.Models.ViewModels;
using RMS.Web.Services;
using RMS.Web.Views.Masters;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity.SqlServer;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Web.Controllers
{
    [Authorize]
    public class MastersController : Controller
    {
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["MVCDBADO"].ConnectionString);
        MVCDBLiveEntities db = new MVCDBLiveEntities();
        MasterServices services = new MasterServices();
        ADOServices treeservice = new ADOServices();
        trialbalanceviewmodel tbmodel = new trialbalanceviewmodel();
        Ptofitlossviewmodel proftlossmodel = new Ptofitlossviewmodel();
        AccGroupTreeView Tree = new AccGroupTreeView();

       
        // GET: Masters
        //------------------Account Groups------------------//
        #region AccountGroup

        public ActionResult AccountGroup()
        {

            var accountgrouplist = db.AccGroup.ToList();

            AccGroup accg = new AccGroup();
            AccountMainHead accm = new AccountMainHead();

            ViewBag.Accundergroup = new SelectList(db.AccGroup, "AccgroupID", "Accgroupname", 0);
            ViewBag.accundergroup = new SelectList(db.AccGroup, "AccgroupID", "Accgroupname", accg.AccunderprimarygroupName);
            ViewBag.Accmain = new SelectList(db.AccountMainHead, "MainGroupID", "MainAccGroupName", accm.MainAccGroupName);


            return View(accountgrouplist);
        }
        [HttpPost]
        public ActionResult SaveAccgroup(int AccgroupID, string Accgroupname, string Accgroupalias, string Accundergroup, string Accunderprimarygroup, int? Accprimarygroupid, int? MainGroupId)
        {

            if (AccgroupID == 0)
            {
                AccGroup acg = new AccGroup();
                acg.Accgroupname = Accgroupname;
                acg.Accgroupalias = Accgroupalias;
                acg.AccunderprimarygroupName = Accunderprimarygroup;
                acg.Accgroupbalance = 0.00;
                int? val = 0;
                if (Accprimarygroupid == null)
                {
                    val = 0;
                }
                else
                {
                    val = Accprimarygroupid;
                }
                acg.Accunderprimarygroupid = val;
                acg.DebitAmount = 0.00;
                acg.CreditAmount = 0.00;
                acg.MainGroupID = MainGroupId;
                var addaccg = acg;

                services.AddAccgrup(addaccg);


                return RedirectToAction("AccountGroup");
            }
            else
            {


                if (AccgroupID > 0)
                {
                    try
                    {

                        var oldaccg = services.Getaccgroupbyid(AccgroupID);


                        //oldaccg.Accgroupbalance = 
                        if (oldaccg.Accunderprimarygroupid != null)
                        {
                            var oldnewaccgrup = services.Getaccgroupbyid(oldaccg.Accunderprimarygroupid);

                        }
                        else
                        {
                            var oldnewaccgrup = services.Getaccgroupbyid(oldaccg.AccgroupID);
                            var oldnewbalance = oldnewaccgrup.Accgroupbalance;
                            var oldnewdebitbalance = oldnewaccgrup.DebitAmount;
                            var oldnewcreditbalance = oldnewaccgrup.CreditAmount;
                            //---------------------Update Account  group 2 credit----------------------------//
                            if (oldnewaccgrup.Accunderprimarygroupid != 0 && oldnewaccgrup.Accunderprimarygroupid != null)
                            {
                                oldnewaccgrup.Accgroupbalance = oldnewbalance - oldaccg.Accgroupbalance;
                                oldnewaccgrup.DebitAmount = oldnewdebitbalance - oldaccg.DebitAmount;
                                oldnewaccgrup.CreditAmount = oldnewcreditbalance - oldaccg.CreditAmount;
                                services.UpdateAccgroup(oldnewaccgrup);

                                var oldnewaccgrup2 = services.Getaccgroupbyid(oldnewaccgrup.Accunderprimarygroupid);
                                var oldnewbalance2 = oldnewaccgrup2.Accgroupbalance;
                                var oldnewdebitbalance2 = oldnewaccgrup2.DebitAmount;
                                var oldnewcreditbalance2 = oldnewaccgrup2.CreditAmount;
                                if (oldnewaccgrup2.Accunderprimarygroupid != 0 && oldnewaccgrup2.Accunderprimarygroupid != null)
                                {
                                    oldnewaccgrup2.Accgroupbalance = oldnewbalance2 - oldaccg.Accgroupbalance;
                                    oldnewaccgrup2.DebitAmount = oldnewdebitbalance2 - oldaccg.DebitAmount;
                                    oldnewaccgrup2.CreditAmount = oldnewcreditbalance2 - oldaccg.CreditAmount;
                                    services.UpdateAccgroup(oldnewaccgrup2);

                                    //---------------------Update Account group 3 credit----------------------------//
                                    var oldnewaccgrup3 = services.Getaccgroupbyid(oldnewaccgrup2.Accunderprimarygroupid);
                                    var oldnewbalance3 = oldnewaccgrup.Accgroupbalance;
                                    var oldnewdebitbalance3 = oldnewaccgrup.DebitAmount;
                                    var oldnewcreditbalance3 = oldnewaccgrup.CreditAmount;
                                    if (oldnewaccgrup3.Accunderprimarygroupid != 0 && oldnewaccgrup3.Accunderprimarygroupid != null)
                                    {
                                        oldnewaccgrup3.Accgroupbalance = oldnewbalance3 - oldaccg.Accgroupbalance;
                                        oldnewaccgrup3.DebitAmount = oldnewdebitbalance3 - oldaccg.DebitAmount;
                                        oldnewaccgrup3.CreditAmount = oldnewcreditbalance3 - oldaccg.CreditAmount;
                                        services.UpdateAccgroup(oldnewaccgrup3);


                                        //---------------------Update Account primary group 4 credit----------------------------//
                                        var oldnewaccgrup4 = services.Getaccgroupbyid(oldnewaccgrup2.Accunderprimarygroupid);
                                        var oldnewbalance4 = oldnewaccgrup.Accgroupbalance;
                                        var oldnewdebitbalance4 = oldnewaccgrup.DebitAmount;
                                        var oldnewcreditbalance4 = oldnewaccgrup.CreditAmount;
                                        if (oldnewaccgrup4.Accunderprimarygroupid != 0 && oldnewaccgrup4.Accunderprimarygroupid != null)
                                        {
                                            oldnewaccgrup4.Accgroupbalance = oldnewbalance4 - oldaccg.Accgroupbalance;
                                            oldnewaccgrup4.DebitAmount = oldnewdebitbalance4 - oldaccg.DebitAmount;
                                            oldnewaccgrup4.CreditAmount = oldnewcreditbalance4 - oldaccg.CreditAmount;
                                            services.UpdateAccgroup(oldnewaccgrup4);


                                            //---------------------Update Account primary group 5 credit----------------------------//
                                            var oldnewaccgrup5 = services.Getaccgroupbyid(oldnewaccgrup2.Accunderprimarygroupid);
                                            var oldnewbalance5 = oldnewaccgrup.Accgroupbalance;
                                            var oldnewdebitbalance5 = oldnewaccgrup.DebitAmount;
                                            var oldnewcreditbalance5 = oldnewaccgrup.CreditAmount;

                                            if (oldnewaccgrup5.Accunderprimarygroupid != 0 && oldnewaccgrup5.Accunderprimarygroupid != null)
                                            {
                                                oldnewaccgrup5.Accgroupbalance = oldnewbalance5 - oldaccg.Accgroupbalance;
                                                oldnewaccgrup5.DebitAmount = oldnewdebitbalance5 - oldaccg.DebitAmount;
                                                oldnewaccgrup5.CreditAmount = oldnewcreditbalance5 - oldaccg.CreditAmount;
                                                services.UpdateAccgroup(oldnewaccgrup5);


                                                //---------------------Update Account primary group 6 credit----------------------------//
                                                var oldnewaccgrup6 = services.Getaccgroupbyid(oldnewaccgrup2.Accunderprimarygroupid);
                                                var oldnewbalance6 = oldnewaccgrup.Accgroupbalance;
                                                var oldnewdebitbalance6 = oldnewaccgrup.DebitAmount;
                                                var oldnewcreditbalance6 = oldnewaccgrup.CreditAmount;

                                                if (oldnewaccgrup6.Accunderprimarygroupid != 0 && oldnewaccgrup6.Accunderprimarygroupid != null)
                                                {
                                                    oldnewaccgrup6.Accgroupbalance = oldnewbalance6 - oldaccg.Accgroupbalance;
                                                    oldnewaccgrup6.DebitAmount = oldnewdebitbalance6 - oldaccg.DebitAmount;
                                                    oldnewaccgrup6.CreditAmount = oldnewcreditbalance6 - oldaccg.CreditAmount;

RMS.Web/Views/Masters/AccountGroup.cshtml
@model IEnumerable<RMS.Web.Models.AccGroup>

@{
    ViewBag.Title = "AccountGroup";
}

<div class="container-fluid">
    <h1 class="col-lg-offset-5 " style="color:slategrey"></h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <button type="button" id="btnadd" class="btn btn-dark" data-target="#exampleModal" data-toggle="modal"><i class="glyphicon glyphicon-plus"></i> Add Account Group</button>

            <h1 class="m-0 font-weight-bold  text-center" style="color:black;">Account Groups</h1>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered " id="dataTable" width="100%" cellspacing="0">
                    <thead class="thead-dark">
                        <tr>
                            <th style="color:white">Account ID</th>
                            <th style="color:white">Account Group Name</th>
                            <th style="color:white">Acount Parent Group </th>
                            @*<th style="color:white">Acount Group Balance</th>
                                <th style="color:white">Acount Debit Total</th>
                                <th style="color:white">Acount Credit Total</th>*@
                            <th style="color:white">Actions</th>
                        </tr>
                    </thead>
                    <tfoot class="thead-dark">
                        <tr>
                            <th style="color:white">Account ID</th>
                            <th style="color:white">Account Group Name</th>
                            <th style="color:white">Acount Parent Group </th>
                            @*<th style="color:white">Acount Group Balance</th>
                                <th style="color:white">Acount Debit Total</th>
                                <th style="color:white">Acount Credit Total</th>*@
                            <th style="color:white">Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.AccgroupID</td>
                                    <td>@item.Accgroupname</td>
                                    <td>@item.AccunderprimarygroupName</td>


                                    @*@if (item.AccUnderGroup == "NULL")
                                        {
                                            <td>   </td>
                                        }
                                        else
                                        {
                                            <td> @item.AccUnderGroup  </td>

                                        }
                                        @if (item.AccunderprimarygroupName == "NULL")
                                        {
                                            <td>  </td>
                                        }
                                        else
                                        {
                                            <td>
                                                @item.AccunderprimarygroupName
                                            </td>

                                        }*@

                                    @*<td>@item.Accgroupbalance</td>
                                        <td>@item.DebitAmount</td>
                                        <td>@item.CreditAmount</td>*@

                                    <td>
                                        <button class="btn btn-primary btnedit" data-id="@item.AccgroupID" data-target="#exampleModal" data-toggle="modal"><i class="glyphicon glyphicon-edit"></i>Edit</button>
                                        @if (item.Accgroupbalance == 0 && item.DebitAmount == 0 && item.CreditAmount == 0)
                                        {
                                            <button data-id="@item.AccgroupID" class="btn btn-danger btndelete"><i class="glyphicon glyphicon-remove"></i>Delete</button>

                                        }

                                    </td>
                                </tr>
                            }
                        }
                    </tbody>




                </table>





            </div>

            <form id="accgroupform">
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-center" id="exampleModalLabel"><strong>Add Account Group</strong></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                @Html.Partial("accgroupartial")
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button id="btnSave" type="button" class="btn btn-primary">Save changes</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script>
    $('#btnadd').click(function () {
        debugger;
        clearmodal();
    });

    function clearmodal() {
        debugger;
        $('#AccgroupID').val(0);
        $('#Accgroupname').val("");
        $('#Accgroupalias').val("");
        $('#Accundergroup2').val("");
        $('#Accmaingrp').val("");
        $('#primarygroup').val(0);
        $('#child2').hide();
        $('#child2L').hide();
        $('#child3').hide();
        $('#child3L').hide();
    };


    $('#btnSave').click(function () {
        var accgid = $(this).attr('data-id');

        debugger;
       var accid = $('#AccgroupID').val();
       var accgname = $('#Accgroupname').val();
       var accgalias = $('#Accgroupalias').val();
        var accundergroup = $('#AccUnderGroup').val();
        var accunderprimarygroup = $('#AccUnderGroup2 option:selected').text();
        var accunderprimarygroupid = $('#AccUnderGroup2 option:selected').val()
        var maingroupid = $('#Accmaingrp option:selected').val()
            $.ajax({
                type: 'POST',
                data: { AccgroupID: accid, Accgroupname: accgname, Accgroupalias: accgalias, Accundergroup: accundergroup, Accunderprimarygroup: accunderprimarygroup, Accprimarygroupid: accunderprimarygroupid, MainGroupId:maingroupid },
                url: "@Url.Action("SaveAccgroup", "Masters")"

            }).done(function (data) {
                if (accid == 0) {
                    alert("account group added successdully");
                    location.reload();
                }
                else {
                    alert("account group updated successdully");
                    location.reload();
                    $('#btnadd').focusin();
                }
            }).fail(function (jqxhr, textStatus) {

                alert("Cant add Account Group ");
            });
    });
    $('.btnedit').click(function () {
        var accgid = $(this).attr('data-id');
        debugger;
       $.ajax({
            type: 'GET',
           data: { AccgroupID: accgid },
            url: "@Url.Action("Getaccgroup", "Masters")"
        }).done(function (data) {
            alert("data caught successfully");
            $('#AccgroupID').val(data.AccgroupID);
            $('#Accgroupname').val(data.Accgroupname);

            if (data.Accgroupalias == null) {
                $('#Accgroupalias').val("no alias");
            }
            else {
                $('#Accgroupalias').val(data.Accgroupalias);
            }
            debugger
            if (data.Accunderprimarygroupid != null) {
                $('#primarygroup').val(2);
                $('#child2').show();
                $('#child2L').show();
                $('#child3').hide();
                $('#child3L').hide();
                $('#AccUnderGroup2').val(data.Accunderprimarygroupid);
            }
            else {
                $('#primarygroup').val(1);
                $('#child2').hide();
                $('#child2L').hide();
                $('#child3').show();
                $('#child3L').show();
                $('#Accmaingrp').val(data.MainGroupID);
            }


            $('#exampleModal').modal('show');

        }).fail(function (jqxhr,textStatus)  {

            alert("Cant get Accgroup details" + textStatus);

        });
    });

    $('.btndelete').click(function () {
        var accid = $(this).attr('data-id');
        var con = confirm("Are u sure u want to delete");
        $(this).parent().parent().remove();
        if (con == true) {

            $.ajax({
                type: 'GET',
                data: { id: accid},
                url: "@Url.Action("Deleteaccgroup","Masters")"

            }).done(function (data) {
                alert("AccGroup Deleted  successfully");


            }).fail(function (jqxhr, textStatus) {

                alert("Cant Deleted  Accgroup ");

            });
        }
        else {
            alert("ok");
        }
    });

    $('#primarygroup').change(function () {
        debugger;
        var pgval = $(this).val();

        $('#Accmaingrp').val("");
        $('#AccUnderGroup2').val("");

        if (pgval == 2) {
            $('#child').hide();
            $('#child2').show();
            $('#child2L').show();
            $('#child3').hide();
            $('#child3L').hide();

        }
        else if (pgval == 1) {
            $('#child2').hide();
            $('#child2L').hide();
            $('#child').hide(400);
            $('#child3').show();
            $('#child3L').show();
        }
        else
        {
            $('#child2').hide();
            $('#child2L').hide();
            $('#child').hide();
            $('#child3').hide();
            $('#child3L').hide();
        }
    });


    @*$(document).ready(function () {
        $("#primarygroup").change(function () {
            debugger;
             if ($('#primarygroup').val() == 1) {
                 $("#child3").css("display", "block");
             }
        });

    });*@
</script>

RMS.Web/Views/Masters/accgroupartial.cshtml
    <input type="hidden" class="form-control" name="AccgroupID" id="AccgroupID" />
    <div class="row">
        <label class="col-md-6">Account Group Name</label>
        <div class="col-md-6">
            <input type="text" class="form-control " id="Accgroupname" name="Accgroupname" />
        </div>
        <hr />
        <br />
        <br />
        <label class="col-md-6">Account Group Alias</label>
        <div class="col-md-6">
            <input type="text" class="form-control " id="Accgroupalias" name="Accgroupalias" />
        </div>
        <br />
        <br />
        <label class="col-md-6">Primary Group</label>

        <div class="col-md-6">
            <select id="primarygroup" class="form-control">
                <option value="0">---Select---</option>
                <option value="1">Yes</option>
                <option value="2">No</option>
            </select>
        </div>
        <br />
        <br />


        <div id="child" style="display:none;" class="col-md-6">
            <input type="text" class="form-control " value="NULL" placeholder="enter account under group" id="AccUnderGroup" name="AccUnderGroup" />
        </div>
        <div id="child2L" style="display:none;" class="col-md-6">
            <label>Account Under Group</label>
        </div>      
        <div id="child2" style="display:none;" class="col-md-6">
            @Html.DropDownList("accundergroup", (IEnumerable<SelectListItem>)ViewBag.accundergroup, "NULL", htmlAttributes: new { @class = "form-control", @Id = "AccUnderGroup2", @Name = "AccUnderGroup2" })
        </div>
        <div id="child3L" class="col-md-6" style="display:none;">
            <label >Account Main Group</label>
        </div>       
        <div id="child3" class="col-md-6" style="display:None;">
            @Html.DropDownList("Accmain", (IEnumerable<SelectListItem>)ViewBag.Accmain, "NULL", htmlAttributes: new { @class = "form-control", @Id = "Accmaingrp", @Name = "Accmaingrp" })
        </div>

        <br />
        <br />
    </div>

RMS.Web/Views/Masters/fgg.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>fgg</title>
</head>
<body>
    <div> 
        <h1></h1>
    </div>
</body>
</html>