RMS.Web/Models/Suppliers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public long SuplierNumber { get; set; }
        public long SuplierCNIC { get; set; }
        public string SupplierAddress { get; set; }
    }
}

RMS.Web/Controllers/SuppliersController.cs
using RMS.Web.Models;
using RMS.Web.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Web.Controllers
{
    public class SuppliersController : Controller
    {
        MVCDBLiveEntities db = new MVCDBLiveEntities();
        SupplierServices Service = new SupplierServices();
        // GET: Suppliers
        public ActionResult Index()
        {
            var list = Service.Getallsupp();
            return View(list);
        }
        [HttpPost]
        public ActionResult SaveSupp(Suppliers Supp)
        {
            if(Supp.SupplierID>0)
            {
                var olddata = Service.Getsuppbyid(Supp.SupplierID);
                olddata.SupplierName = Supp.SupplierName;
                olddata.SuplierNumber = Supp.SuplierNumber;
                olddata.SuplierCNIC = Supp.SuplierCNIC;
                olddata.SupplierAddress = Supp.SupplierAddress;
                Service.Updatesupp(olddata);
                return RedirectToAction("Index");


            }
            else
            {
                if(Supp.SupplierName!=null)
                {
                    Service.Addsupp(Supp);
                    return RedirectToAction("Index");

                }
                return RedirectToAction("Index");

            }

        }
        public ActionResult Getsupp(int suppid)
        {
            var getsupp = Service.Getsuppbyid(suppid);

            Suppliers supp = new Suppliers();
            supp.SupplierID = getsupp.SupplierID;
            supp.SupplierName = getsupp.SupplierName;
            supp.SuplierNumber = getsupp.SuplierNumber;
            supp.SuplierCNIC = getsupp.SuplierCNIC;
            supp.SupplierAddress = getsupp.SupplierAddress;


            return Json(supp, JsonRequestBehavior.AllowGet);

        }
        public ActionResult DeleteSupp(int SupplierID)
        {
            var oldsupp = Service.Getsuppbyid(SupplierID);
            Service.Deletesupplier(oldsupp);

            return RedirectToAction("Index");
        }

    }
}

RMS.Web/Views/Suppliers/Index.cshtml
@model List<RMS.Web.Models.Suppliers>

@{
    ViewBag.Title = "Index";
}


    <div class="container-fluid">
        <h1 class="col-lg-offset-5 " style="color:slategrey"></h1>
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <button class="btn btn-primary" id="btnadd" data-target="#exampleModal" data-toggle="modal">Add Suppliers</button>

                <h1 class="m-0 font-weight-bold text-primary text-center">Suppliers</h1>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead style="background-color:yellow">
                            <tr>
                                <th>Supplier Name</th>
                                <th>Supplier Number</th>
                                <th>Supplier CNIC</th>
                                <th>Supplier Address</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.SupplierName</td>
                                        <td>@item.SuplierNumber</td>
                                        <td>@item.SuplierCNIC</td>
                                        <td>@item.SupplierAddress</td>
                                        <td><button class="btn btn-primary btnedit" data-target="#exampleModal" data-toggle="modal" data-id="@item.SupplierID"><i class="glyphicon glyphicon-edit"></i>Edit</button>
                                        <button class="btn btn-danger btndelete" data-id="@item.SupplierID"><i class="glyphicon glyphicon-remove"></i>Delete</button></td>
                                    </tr>
                                }
                            }
                        </tbody>




                    </table>
                    @*<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title text-center" id="exampleModalLabel"><strong>Add Supplier </strong></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    @Html.Partial("partialsupp")
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button id="btnSave" type="button" class="btn btn-primary">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>*@
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title text-center" id="exampleModalLabel"><strong>Add Item Form</strong></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    @Html.Partial("partialsupp")
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button id="btnSave" type="button" class="btn btn-primary">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


                </div>
            </div>
        </div>


<script>


    $('#btnadd').click(function () {
        debugger;
        $('#SupplierID').val(0);
        $('#SupplierName').val("");
        $('#SuplierNumber').val("");
        $('#SuplierCNIC').val("");
        $('#SupplierAddress').val("");
        debugger;
       
        
    });

    $('#btnSave').click(function () {
        suppid = $('#SupplierID').val();
        if (suppid <= 0) {
            confirm("Are U sure u want to Add");
        }
        else  {
            confirm("Are U sure you want to update");

        }

        $.ajax({
            type: 'POST',
            data: $('#supplierform').serialize(),
            url: "@Url.Action("SaveSupp","Suppliers")"

        }).done(function (data) {
            location.reload();
            debugger;
            if (suppid <= 0) {
                alert("Supplier Added Successfully")
               
                $('table > tbody > tr > 0').css("background-color", "grey");
                
            }
            else {
                alert("Supplier Updated  Successfully")
            }

            }).fail(function (jqxhr, textStatus) {

                alert("Supplier save Failed, Contact to Admin");

            });


    });
   $('.btndelete').click(function () {
       var suppid = $(this).attr('data-id');

       var con = confirm("Are u sure u want to delete");
       if (con == true) {

           debugger;
           $.ajax({

               type: 'GET',
               data: { SupplierID: suppid },
              url: "@Url.Action("DeleteSupp", "Suppliers")",
           }).done(function (data) {

               alert("Supplier deleted Successfully");
               location.reload();

           }).fail(function (jqxhr, textStatus) {

               alert("Cant delete supplier");

           });
       }
       else {
           alert("ok");
       }
      


   });
    $(document).ready(function (){

    $('.btnedit').click(function () {
        var suppidd = $(this).attr('data-id');

        debugger;
        $.ajax({
            type: 'GET',
            data: { suppid: suppidd },
            url: "@Url.Action("Getsupp","Suppliers")"
        }).done(function (data) {
            alert("data caught successfully");
            $('#SupplierID').val(data.SupplierID);
            $('#SupplierName').val(data.SupplierName);
            $('#SuplierNumber').val(data.SuplierNumber);
            $('#SuplierCNIC').val(data.SuplierCNIC);
            $('#SupplierAddress').val(data.SupplierAddress);

            $('#exampleModal').modal('show');

        }).fail(function (jqxhr,textStatus)  {

            alert("Cant get supplier details");

        });






    });










    });







</script>

RMS.Web/Views/Suppliers/partialsupp.cshtml
<form id="supplierform">

    <input type="hidden" class="form-control" name="SupplierID" id="SupplierID" />
    <div class="row">
        <input type="number" hidden id="SupplierID" />
        <label class="col-sm-5" >Supplier Name</label>
        <input type="text" required class="form-control" id="SupplierName" name="SupplierName" />
        <hr />
        <label class="col-sm-5">Supplier Number</label>
        <input type="text" required class="form-control" id="SuplierNumber" name="SuplierNumber" />
        <hr />
        <label class="col-sm-5">Supplir CNIC</label>
        <input required class="form-control" id="SuplierCNIC" name="SuplierCNIC" />
        <hr />
        <label class="col-sm-5">Supplier Address</label>
        <input required class="form-control" id="SupplierAddress" name="SupplierAddress" />
    </div>











</form>